name: 'Build'

on:
  push:
    branches:
      - main

jobs:
  cancel_previous_workflow:
    runs-on: ubuntu-20.04
    steps:
      - name: 'Cancel previous workflow'
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

  create_exe_file:
    runs-on: ubuntu-20.04
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Setup Python'
        uses: actions/setup-python@v2
        with:
          python: 3.8

      - name: 'Install dependencies'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 'Build executable for Windows'
        run: pyinstaller --onefile --noconsole --name testName --icon source/data/assets/icon.ico source/main.py

      - name: 'show '
        run: 'ls -l'
