name: 'Build'

on:
  push:
    branches:
      - main

jobs:
  cancel_previous_workflow:
    runs-on: ubuntu-20.04
    steps:
      - name: 'Cancel previous workflow'
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

  create_exe_file:
    runs-on: windows-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Setup Python'
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: 'Install dependencies'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 'Build executable for Windows'
        run: pyinstaller --onefile --noconsole --name testName --icon source/data/assets/icon.ico source/main.py

      - name: 'Create a release'
        uses: svenstaro/upload-release-action@v2
        with:
          release_name: 'testName ${{ github.ref }}'
          asset_name: 'testName.exe | Windows'
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./dist/testName.exe
          tag: ${{ github.ref }}
          overwrite: true
          body: 'testName | Executable for Windows'
